using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
/*
 * Este script se encarga de controlar al jugador en un Roll a Ball
 */
public class PlayerControllerPrueba : MonoBehaviour
{
    private Rigidbody rb;
    private float movementX;
    private float movementY;
    
    public float speedPrueba = 0;
    
    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        Debug.Log("Hola, debugueando");
    }
    
    private void FixedUpdate(){
        Vector3 movement = new Vector3 (movementX, 0.0f, movementY);
        rb.AddForce(movement * speedPrueba);
        // Si la bola se sale del plano, se reinicia
        if (transform.position.y < -10){
            transform.position = new Vector3(0, 0.5f, 0);
            rb.velocity = Vector3.zero;
        }
    }
    
    void OnMove(InputValue movementValue){
        Vector2 movementVector = movementValue.Get<Vector2>();
        Debug.Log(movementVector);
        
        movementX = movementVector.x*2; 
        movementY = movementVector.y*2;
        
    }

    /*
     * Este m√©todo se encarga de detectar cuando se presiona la barra espaciadora
     */
    void OnFire()
    {
        Debug.Log("Fire!");
    }
}
